window.PARIS_DATA = {
  "version": 1,
  "places": {
    "home": {
      "id": "home",
      "name": "숙소",
      "address": "60 Rue du Vertbois, 75003 Paris",
      "query": "60 Rue du Vertbois, 75003 Paris",
      "latlng": [
        48.867439,
        2.356411
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=60+Rue+du+Vertbois+75003+Paris&limit=1",
      "url": "",
      "detail": ""
    },
    "cdg": {
      "id": "cdg",
      "name": "CDG · Terminal 1",
      "address": "Paris Charles de Gaulle · Terminal 1",
      "query": "Charles de Gaulle Airport Terminal 1 France",
      "latlng": [
        49.0144171,
        2.541848
      ],
      "source": "https://nominatim.openstreetmap.org/lookup?osm_ids=R8473005&format=json",
      "url": "https://www.parisaeroport.fr/en/passengers/transport-parking/public-transport-paris/rer-b/cdg",
      "detail": ""
    },
    "partisan": {
      "id": "partisan",
      "name": "Partisan Café Artisanal",
      "address": "36 Rue de Turbigo, 75003 Paris",
      "query": "Partisan Café Artisanal 36 Rue de Turbigo Paris",
      "latlng": [
        48.864661,
        2.35303
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=36+Rue+de+Turbigo+75003+Paris&limit=1",
      "url": "https://www.parispartisancafe.com/",
      "detail": ""
    },
    "dsm": {
      "id": "dsm",
      "name": "Dover Street Market Paris",
      "address": "35–37 Rue des Francs-Bourgeois, Paris",
      "query": "Dover Street Market Paris 35 Rue des Francs Bourgeois",
      "latlng": [
        48.857787,
        2.360391
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=35+Rue+des+Francs+Bourgeois+75004+Paris&limit=1",
      "url": "https://www.doverstreetmarketparis.com/pages/locations",
      "detail": ""
    },
    "pompidou": {
      "id": "pompidou",
      "name": "Maison Pompidou",
      "address": "50 Rue Rambuteau, 75003 Paris",
      "query": "Maison Pompidou 50 Rue Rambuteau Paris",
      "latlng": [
        48.861592,
        2.352245
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=50+Rue+Rambuteau+75003+Paris&limit=1",
      "url": "https://www.centrepompidou.fr/en/lieu/maison-pompidou",
      "detail": "무료 · 화요일 휴관 · 11:00–19:00. 본관과 다른 공간."
    },
    "mesures": {
      "id": "mesures",
      "name": "Mesures",
      "address": "58 Rue de Saintonge, Paris",
      "query": "Mesures 58 Rue de Saintonge Paris",
      "latlng": [
        48.863216,
        2.364274
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=58+Rue+de+Saintonge+75003+Paris&limit=1",
      "url": "https://www.timeout.fr/paris/bars/mesures",
      "detail": "음악 바 · 첫날 저녁 선택 일정"
    },
    "large": {
      "id": "large",
      "name": "Large",
      "address": "Île Seguin, Boulogne-Billancourt",
      "query": "Large Emerige Île Seguin Boulogne Billancourt",
      "latlng": [
        48.8245002,
        2.2321323
      ],
      "source": "https://nominatim.openstreetmap.org/search?q=%C3%8Ele+Seguin+Boulogne-Billancourt+France&format=json&limit=1",
      "url": "https://www.large-emerige.fr/",
      "detail": "10/17–18 개관 주말 · 입장 방식 확인 필요. 지도는 섬 기준."
    },
    "babylone": {
      "id": "babylone",
      "name": "Saint Laurent Babylone",
      "address": "9 Rue de Grenelle, Paris",
      "query": "Saint Laurent Babylone 9 Rue de Grenelle Paris",
      "latlng": [
        48.85282,
        2.329138
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=9+Rue+de+Grenelle+75007+Paris&limit=1",
      "url": "https://www.ysl.com/fr-fr/stores/saint-laurent-babylone-30307",
      "detail": ""
    },
    "nanna": {
      "id": "nanna",
      "name": "NANNA",
      "address": "Port de Montebello, 75005 Paris",
      "query": "NANNA Port de Montebello Paris",
      "latlng": [
        48.851539,
        2.349803
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=7+Quai+de+Montebello+75005+Paris&limit=1",
      "url": "https://nanna-paris.fr/",
      "detail": "7 Quai de Montebello 앞 계단 진입 · 매일 12:00부터"
    },
    "orangerie": {
      "id": "orangerie",
      "name": "Musée de l’Orangerie",
      "address": "Jardin des Tuileries, 75001 Paris",
      "query": "Musée de l’Orangerie Paris",
      "latlng": [
        48.8637655,
        2.3226602
      ],
      "source": "https://nominatim.openstreetmap.org/search?q=Mus%C3%A9e+de+l%E2%80%99Orangerie+Paris&format=json&limit=1",
      "url": "https://www.musee-orangerie.fr/fr/visite/acces-horaires-tarifs",
      "detail": ""
    },
    "grand": {
      "id": "grand",
      "name": "Le Grand Café",
      "address": "1 Place Clemenceau, 75008 Paris",
      "query": "Le Grand Café 1 Place Clemenceau Paris",
      "latlng": [
        48.867052,
        2.313214
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=1+Place+Clemenceau+75008+Paris&limit=1",
      "url": "https://www.legrandcafe-paris.com/",
      "detail": ""
    },
    "pinault": {
      "id": "pinault",
      "name": "Bourse de Commerce · Pinault Collection",
      "address": "2 Rue de Viarmes, 75001 Paris",
      "query": "Bourse de Commerce Pinault Collection Paris",
      "latlng": [
        48.862946,
        2.3424
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=2+Rue+de+Viarmes+75001+Paris&limit=1",
      "url": "https://www.pinaultcollection.com/en/boursedecommerce/remember-me",
      "detail": ""
    },
    "shin": {
      "id": "shin",
      "name": "Café Shin Palais Royal",
      "address": "28 bis Rue de Richelieu, 75001 Paris",
      "query": "Café Shin Palais Royal 28 bis Rue de Richelieu Paris",
      "latlng": [
        48.865229,
        2.336707
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=28+Rue+de+Richelieu+75001+Paris&limit=1",
      "url": "https://www.pagesjaunes.fr/pros/64990741",
      "detail": "지도는 28번지 주소 기준"
    },
    "canal": {
      "id": "canal",
      "name": "Canal Saint-Martin",
      "address": "Quai de Valmy, 75010 Paris",
      "query": "Canal Saint Martin Quai de Valmy Paris",
      "latlng": [
        48.876098,
        2.365589
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=Quai+de+Valmy+75010+Paris&limit=1",
      "url": "",
      "detail": "지도는 운하 산책 구간의 대표 지점"
    },
    "bouillon": {
      "id": "bouillon",
      "name": "Bouillon République",
      "address": "39 Boulevard du Temple, Paris",
      "query": "Bouillon République 39 Boulevard du Temple Paris",
      "latlng": [
        48.866021,
        2.364706
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=39+Boulevard+du+Temple+75003+Paris&limit=1",
      "url": "https://bouillonlesite.com/",
      "detail": ""
    },
    "nord": {
      "id": "nord",
      "name": "Gare du Nord",
      "address": "18 Rue de Dunkerque, 75010 Paris",
      "query": "Gare du Nord Paris",
      "latlng": [
        48.88038,
        2.35355
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=18+Rue+de+Dunkerque+75010+Paris&limit=1",
      "url": "",
      "detail": ""
    },
    "ams": {
      "id": "ams",
      "name": "Amsterdam Centraal",
      "address": "Stationsplein, Amsterdam",
      "query": "Amsterdam Centraal Netherlands",
      "latlng": [
        52.378901,
        4.9005805
      ],
      "source": "https://nominatim.openstreetmap.org/search?q=Amsterdam+Centraal+Netherlands&format=json&limit=1",
      "url": "",
      "detail": ""
    },
    "reaumur": {
      "id": "reaumur",
      "name": "Réaumur–Sébastopol",
      "address": "Réaumur–Sébastopol, Paris",
      "query": "Réaumur Sébastopol Metro Paris",
      "latlng": [
        48.8662481,
        2.3526084
      ],
      "source": "https://nominatim.openstreetmap.org/search?q=R%C3%A9aumur+S%C3%A9bastopol+Paris&format=json&limit=1",
      "url": "https://www.bonjour-ratp.fr/lignes-metro/ligne-4/",
      "detail": ""
    },
    "mitterrand": {
      "id": "mitterrand",
      "name": "Galerie Mitterrand",
      "address": "28 Avenue Matignon, Paris",
      "query": "Galerie Mitterrand 28 Avenue Matignon Paris",
      "latlng": [
        48.871594,
        2.314222
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=28+Avenue+Matignon+75008+Paris&limit=1",
      "url": "https://www.artnewspaper.fr/2026/09/07/la-galerie-mitterrand-setend-avenue-matignon",
      "detail": "10/20 대체 후보 · 일반 공개 시간 확인 후 방문"
    },
    "cartilage": {
      "id": "cartilage",
      "name": "Cartilage",
      "address": "210 Rue du Faubourg-Saint-Antoine, Paris",
      "query": "Cartilage 210 Rue du Faubourg Saint Antoine Paris",
      "latlng": [
        48.849728,
        2.386208
      ],
      "source": "https://data.geopf.fr/geocodage/search?q=210+Rue+du+Faubourg+Saint+Antoine+75012+Paris&limit=1",
      "url": "https://www.timeout.fr/paris/actualites/cartilage-nouveau-lieu-scenes-alternatives-ancien-cabaret-libanais-030526",
      "detail": "10/17 Mesures 대체 후보 · 공연·입장료 미확인"
    },
    "marais": {
      "id": "marais",
      "name": "Le Marais",
      "address": "Le Marais, Paris",
      "query": "restaurants Le Marais Paris",
      "latlng": null,
      "source": null,
      "url": "",
      "detail": ""
    },
    "saintgermain": {
      "id": "saintgermain",
      "name": "Saint-Germain-des-Prés",
      "address": "Saint-Germain-des-Prés, Paris",
      "query": "Saint Germain des Pres Paris",
      "latlng": null,
      "source": null,
      "url": "",
      "detail": ""
    },
    "palais": {
      "id": "palais",
      "name": "Palais-Royal",
      "address": "Palais Royal, Paris",
      "query": "Palais Royal Paris",
      "latlng": null,
      "source": null,
      "url": "",
      "detail": ""
    }
  },
  "days": [
    {
      "day": 17,
      "date": "2026-10-17",
      "weekday": "토",
      "title": "도착 · Le Marais",
      "region": "Partisan · Dover Street Market · Maison Pompidou",
      "important": "07:20 CDG 도착 · 13:00 체크인",
      "brief": "짐 보관은 숙소에 미리 확인",
      "items": [
        {
          "id": "d17-0",
          "day": 17,
          "start": "07:20",
          "end": "",
          "after": false,
          "title": "파리 도착",
          "note": "",
          "place": "cdg",
          "key": true,
          "transit": false,
          "fixed": true,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-1",
          "day": 17,
          "start": "07:20",
          "end": "09:10",
          "after": false,
          "title": "입국 수속·수하물 수령",
          "note": "대기 여유 포함",
          "place": "cdg",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-2",
          "day": 17,
          "start": "09:10",
          "end": "10:40",
          "after": false,
          "title": "공항 → 숙소 주변",
          "note": "CDGVAL → RER B → Gare du Nord → 메트로 4호선 → Réaumur–Sébastopol. 정상 운행 기준.",
          "place": "home",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-3",
          "day": 17,
          "start": "10:40",
          "end": "11:00",
          "after": false,
          "title": "짐 보관",
          "note": "숙소 사전 협의 · 불가하면 인근 유료 보관소",
          "place": "home",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": "bag-in"
        },
        {
          "id": "d17-4",
          "day": 17,
          "start": "11:00",
          "end": "12:00",
          "after": false,
          "title": "Partisan Café Artisanal",
          "note": "커피·가벼운 아침",
          "place": "partisan",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-5",
          "day": 17,
          "start": "12:00",
          "end": "12:45",
          "after": false,
          "title": "점심",
          "note": "숙소 주변에서 간단히",
          "place": "home",
          "key": false,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-6",
          "day": 17,
          "start": "13:00",
          "end": "14:15",
          "after": false,
          "title": "체크인 · 휴식",
          "note": "",
          "place": "home",
          "key": true,
          "transit": false,
          "fixed": true,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-7",
          "day": 17,
          "start": "14:15",
          "end": "14:40",
          "after": false,
          "title": "Le Marais로 이동",
          "note": "도보 여유 포함",
          "place": "dsm",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-8",
          "day": 17,
          "start": "14:40",
          "end": "16:00",
          "after": false,
          "title": "Dover Street Market Paris",
          "note": "편집숍·공간 구경",
          "place": "dsm",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-9",
          "day": 17,
          "start": "16:00",
          "end": "16:15",
          "after": false,
          "title": "Maison Pompidou로 이동",
          "note": "도보",
          "place": "pompidou",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-10",
          "day": 17,
          "start": "16:15",
          "end": "17:00",
          "after": false,
          "title": "Maison Pompidou",
          "note": "2026년 신규 공간 · 무료",
          "place": "pompidou",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-11",
          "day": 17,
          "start": "17:00",
          "end": "17:30",
          "after": false,
          "title": "Le Marais 골목 산책·숙소 복귀",
          "note": "첫날 컨디션에 따라 산책 생략",
          "place": "home",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-12",
          "day": 17,
          "start": "17:30",
          "end": "18:45",
          "after": false,
          "title": "숙소 휴식",
          "note": "첫날 체력 조절",
          "place": "home",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-13",
          "day": 17,
          "start": "19:00",
          "end": "20:00",
          "after": false,
          "title": "저녁",
          "note": "",
          "place": "marais",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d17-14",
          "day": 17,
          "start": "20:00",
          "end": "21:00",
          "after": false,
          "title": "Mesures",
          "note": "음악 바",
          "place": "mesures",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": true,
          "booking": ""
        },
        {
          "id": "d17-15",
          "day": 17,
          "start": "21:00",
          "end": "",
          "after": true,
          "title": "숙소 복귀",
          "note": "피곤하면 저녁 이후 바로 복귀",
          "place": "home",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        }
      ],
      "route": [
        "cdg",
        "home",
        "partisan",
        "home",
        "dsm",
        "pompidou",
        "home",
        "mesures",
        "home"
      ],
      "modes": [
        "transit",
        "walking",
        "walking",
        "walking",
        "walking",
        "walking",
        "walking",
        "walking"
      ]
    },
    {
      "day": 18,
      "date": "2026-10-18",
      "weekday": "일",
      "title": "Large · Saint-Germain",
      "region": "Île Seguin · Saint Laurent Babylone · NANNA",
      "important": "11:00 Large 입장 예정",
      "brief": "개관 주말 입장 방식 확인 · 이동 60–75분",
      "items": [
        {
          "id": "d18-0",
          "day": 18,
          "start": "09:00",
          "end": "09:40",
          "after": false,
          "title": "아침 식사",
          "note": "숙소 주변",
          "place": "home",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d18-1",
          "day": 18,
          "start": "09:45",
          "end": "11:00",
          "after": false,
          "title": "Île Seguin으로 이동",
          "note": "대중교통·도보 60–75분을 잡은 계획안",
          "place": "large",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d18-2",
          "day": 18,
          "start": "11:00",
          "end": "13:00",
          "after": false,
          "title": "Large",
          "note": "Moteur Imaginaire · 개관 주말 입장 방식·시간·요금 확인 후 예약.",
          "place": "large",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": "large"
        },
        {
          "id": "d18-3",
          "day": 18,
          "start": "13:00",
          "end": "14:00",
          "after": false,
          "title": "점심",
          "note": "Île Seguin·인근 식당",
          "place": "large",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d18-4",
          "day": 18,
          "start": "14:00",
          "end": "14:40",
          "after": false,
          "title": "Île Seguin 강변·건축 산책",
          "note": "비가 오거나 피곤하면 생략",
          "place": "large",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": true,
          "booking": ""
        },
        {
          "id": "d18-5",
          "day": 18,
          "start": "14:40",
          "end": "15:45",
          "after": false,
          "title": "Saint-Germain-des-Prés으로 이동",
          "note": "대중교통·도보 여유 포함",
          "place": "babylone",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d18-6",
          "day": 18,
          "start": "15:45",
          "end": "16:00",
          "after": false,
          "title": "휴식·이동 여유",
          "note": "Saint-Germain-des-Prés",
          "place": "saintgermain",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d18-7",
          "day": 18,
          "start": "16:00",
          "end": "16:45",
          "after": false,
          "title": "Saint Laurent Babylone",
          "note": "아트북·레코드 구경",
          "place": "babylone",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d18-8",
          "day": 18,
          "start": "16:45",
          "end": "17:15",
          "after": false,
          "title": "Notre-Dame·NANNA 방향 이동",
          "note": "도보",
          "place": "nanna",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d18-9",
          "day": 18,
          "start": "17:15",
          "end": "18:15",
          "after": false,
          "title": "NANNA",
          "note": "Notre-Dame 앞 선상 독서공간·바. 7 Quai de Montebello 앞 계단 진입.",
          "place": "nanna",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d18-10",
          "day": 18,
          "start": "18:15",
          "end": "19:00",
          "after": false,
          "title": "숙소 주변으로 복귀",
          "note": "이동·휴식",
          "place": "home",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d18-11",
          "day": 18,
          "start": "19:00",
          "end": "20:00",
          "after": false,
          "title": "저녁",
          "note": "숙소 주변",
          "place": "home",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d18-12",
          "day": 18,
          "start": "20:00",
          "end": "",
          "after": true,
          "title": "숙소 휴식",
          "note": "다음 날 미술관 일정 준비",
          "place": "home",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        }
      ],
      "route": [
        "home",
        "large",
        "babylone",
        "nanna",
        "home"
      ],
      "modes": [
        "transit",
        "transit",
        "walking",
        "transit"
      ]
    },
    {
      "day": 19,
      "date": "2026-10-19",
      "weekday": "월",
      "title": "미술관 · Grand Palais",
      "region": "Musée de l’Orangerie · Pinault Collection",
      "important": "09:00 관람 · 12:00 점심 · 14:30 관람",
      "brief": "미술관 2곳과 Le Grand Café 예약 확인",
      "items": [
        {
          "id": "d19-0",
          "day": 19,
          "start": "08:00",
          "end": "08:45",
          "after": false,
          "title": "아침·Musée de l’Orangerie 이동",
          "note": "간단히 먹고 출발",
          "place": "orangerie",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d19-1",
          "day": 19,
          "start": "08:45",
          "end": "09:00",
          "after": false,
          "title": "입장 대기",
          "note": "예약 시간보다 조금 일찍 도착",
          "place": "orangerie",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d19-2",
          "day": 19,
          "start": "09:00",
          "end": "11:00",
          "after": false,
          "title": "Musée de l’Orangerie",
          "note": "수련 + Monet, peindre le temps. 09:00 예약 권장.",
          "place": "orangerie",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": "orangerie"
        },
        {
          "id": "d19-3",
          "day": 19,
          "start": "11:00",
          "end": "11:45",
          "after": false,
          "title": "Jardin des Tuileries·Place de la Concorde → Grand Palais",
          "note": "산책·이동",
          "place": "grand",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d19-4",
          "day": 19,
          "start": "12:00",
          "end": "13:15",
          "after": false,
          "title": "Le Grand Café",
          "note": "1인 예약 권장",
          "place": "grand",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": "grand"
        },
        {
          "id": "d19-5",
          "day": 19,
          "start": "13:15",
          "end": "14:15",
          "after": false,
          "title": "Bourse de Commerce로 이동",
          "note": "이동·휴식 여유 포함",
          "place": "pinault",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d19-6",
          "day": 19,
          "start": "14:15",
          "end": "14:30",
          "after": false,
          "title": "입장 준비",
          "note": "Bourse de Commerce",
          "place": "pinault",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d19-7",
          "day": 19,
          "start": "14:30",
          "end": "17:00",
          "after": false,
          "title": "Bourse de Commerce · Pinault Collection",
          "note": "Remember Me + Barbara Kruger: The History of Tears. 14:30 예약 권장.",
          "place": "pinault",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": "pinault"
        },
        {
          "id": "d19-8",
          "day": 19,
          "start": "17:00",
          "end": "17:30",
          "after": false,
          "title": "Palais-Royal 방향 산책",
          "note": "도보",
          "place": "palais",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d19-9",
          "day": 19,
          "start": "17:30",
          "end": "18:15",
          "after": false,
          "title": "Café Shin Palais Royal",
          "note": "커피",
          "place": "shin",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d19-10",
          "day": 19,
          "start": "19:00",
          "end": "20:00",
          "after": false,
          "title": "저녁",
          "note": "Palais-Royal·Montorgueil 또는 숙소 주변",
          "place": "palais",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d19-11",
          "day": 19,
          "start": "20:00",
          "end": "",
          "after": true,
          "title": "숙소 복귀·짐 정리",
          "note": "체크아웃 준비",
          "place": "home",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        }
      ],
      "route": [
        "home",
        "orangerie",
        "grand",
        "pinault",
        "shin",
        "home"
      ],
      "modes": [
        "transit",
        "walking",
        "transit",
        "walking",
        "walking"
      ]
    },
    {
      "day": 20,
      "date": "2026-10-20",
      "weekday": "화",
      "title": "체크아웃 · Amsterdam",
      "region": "Canal Saint-Martin · Gare du Nord",
      "important": "16:18 Gare du Nord 출발",
      "brief": "14:15 짐 수령 · 역 도착 목표 15:20",
      "items": [
        {
          "id": "d20-0",
          "day": 20,
          "start": "08:30",
          "end": "10:30",
          "after": false,
          "title": "아침·짐 정리",
          "note": "숙소 주변",
          "place": "home",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d20-1",
          "day": 20,
          "start": "11:00",
          "end": "",
          "after": false,
          "title": "체크아웃·짐 보관",
          "note": "숙소 보관 가능 여부 확인 필요",
          "place": "home",
          "key": true,
          "transit": false,
          "fixed": true,
          "optional": false,
          "booking": "bag-out"
        },
        {
          "id": "d20-2",
          "day": 20,
          "start": "11:15",
          "end": "12:15",
          "after": false,
          "title": "Canal Saint-Martin 산책",
          "note": "짧게 걷는 일정",
          "place": "canal",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d20-3",
          "day": 20,
          "start": "12:30",
          "end": "13:30",
          "after": false,
          "title": "Bouillon République",
          "note": "대기가 길면 인근 식당으로 변경",
          "place": "bouillon",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d20-4",
          "day": 20,
          "start": "13:30",
          "end": "14:15",
          "after": false,
          "title": "숙소·보관소로 복귀",
          "note": "마지막 커피·이동 여유",
          "place": "home",
          "key": false,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d20-5",
          "day": 20,
          "start": "14:15",
          "end": "14:45",
          "after": false,
          "title": "짐 수령",
          "note": "이후 추가 관광 없음",
          "place": "home",
          "key": true,
          "transit": false,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d20-6",
          "day": 20,
          "start": "14:45",
          "end": "15:20",
          "after": false,
          "title": "Gare du Nord으로 이동",
          "note": "Réaumur–Sébastopol → 메트로 4호선 → Gare du Nord. Gare du Nord 도착 목표 15:20.",
          "place": "nord",
          "key": true,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d20-7",
          "day": 20,
          "start": "15:20",
          "end": "16:00",
          "after": false,
          "title": "승강장 확인 · 탑승 준비",
          "note": "Gare du Nord 도착 목표 15:20",
          "place": "nord",
          "key": true,
          "transit": true,
          "fixed": false,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d20-8",
          "day": 20,
          "start": "16:18",
          "end": "",
          "after": false,
          "title": "Gare du Nord 출발",
          "note": "열차 9463",
          "place": "nord",
          "key": true,
          "transit": false,
          "fixed": true,
          "optional": false,
          "booking": ""
        },
        {
          "id": "d20-9",
          "day": 20,
          "start": "19:50",
          "end": "",
          "after": false,
          "title": "Amsterdam Centraal 도착",
          "note": "이동 시간 3시간 32분",
          "place": "ams",
          "key": true,
          "transit": false,
          "fixed": true,
          "optional": false,
          "booking": ""
        }
      ],
      "route": [
        "home",
        "canal",
        "bouillon",
        "home",
        "nord",
        "ams"
      ],
      "modes": [
        "walking",
        "walking",
        "walking",
        "transit",
        "transit"
      ]
    }
  ],
  "bookings": [
    {
      "id": "large",
      "title": "Large",
      "when": "10/18 11:00",
      "note": "개관전 Moteur Imaginaire · 일반권 €15 예정. 개관 주말 입장 방식·무료 여부·잔여석 미확인.",
      "url": "https://www.large-emerige.fr/",
      "place": "large",
      "type": "booking"
    },
    {
      "id": "orangerie",
      "title": "Musée de l’Orangerie",
      "when": "10/19 09:00",
      "note": "수련 + Monet, peindre le temps · 온라인 일반권 €12.50 (첨부 기준).",
      "url": "https://www.musee-orangerie.fr/fr/visite/tarifs-orangerie",
      "place": "orangerie",
      "type": "booking"
    },
    {
      "id": "grand",
      "title": "Le Grand Café",
      "when": "10/19 12:00 · 1명",
      "note": "Grand Palais · 점심 예약 권장.",
      "url": "https://www.legrandcafe-paris.com/",
      "place": "grand",
      "type": "booking"
    },
    {
      "id": "pinault",
      "title": "Bourse de Commerce · Pinault Collection",
      "when": "10/19 14:30",
      "note": "Remember Me + Barbara Kruger 설치 · 일반권 €15 (첨부 기준).",
      "url": "https://www.pinaultcollection.com/fr/boursedecommerce/history-tears",
      "place": "pinault",
      "type": "booking"
    },
    {
      "id": "bag-in",
      "title": "체크인 전 짐 보관",
      "when": "10/17 10:40",
      "note": "숙소에 미리 확인. 불가하면 인근 유료 보관소 이용.",
      "url": "",
      "place": "home",
      "type": "check"
    },
    {
      "id": "bag-out",
      "title": "체크아웃 후 짐 보관",
      "when": "10/20 11:00 → 14:15 수령",
      "note": "보관 가능 여부·수령 장소 확인. 14:45까지 짐 수령을 마치고 Gare du Nord으로 출발.",
      "url": "",
      "place": "home",
      "type": "check"
    }
  ],
  "alternatives": [
    {
      "place": "mitterrand",
      "day": 20,
      "title": "10/20 · Galerie Mitterrand 대체안",
      "note": "일반 공개 시간 확인 후 운하·점심 구간과 교체. 11:00–11:45 이동 → 11:45–12:30 방문 → 12:30–13:15 점심 → 14:15 숙소 복귀. 짐 수령·Gare du Nord 일정은 유지."
    },
    {
      "place": "cartilage",
      "day": 17,
      "title": "10/17 · Cartilage",
      "note": "당일 공연·DJ·입장료 확인 후 선택."
    },
    {
      "place": "pompidou",
      "day": 19,
      "title": "첫날 Maison Pompidou를 생략했다면",
      "note": "10/19 Pinault Collection 관람 후 Café Shin 대신 방문. 19:00 종료 전 관람 가능 시간 확인."
    }
  ],
  "packing": [
    "여권·항공권·열차표",
    "숙소·짐 보관 확인",
    "미술관·점심 예약",
    "로밍·eSIM",
    "충전기·보조배터리",
    "우산·편한 신발"
  ],
  "sources": {
    "airport": "https://www.parisaeroport.fr/en/passengers/transport-parking/public-transport-paris/rer-b/cdg",
    "metro4": "https://www.bonjour-ratp.fr/lignes-metro/ligne-4/",
    "partisan": "https://www.parispartisancafe.com/",
    "dsm": "https://www.doverstreetmarketparis.com/pages/locations",
    "mesures": "https://www.timeout.fr/paris/bars/mesures",
    "pompidou": "https://www.centrepompidou.fr/en/lieu/maison-pompidou",
    "paris-openings": "https://parisjetaime.com/article/nouveaux-lieux-paris-a1056",
    "nanna": "https://nanna-paris.fr/",
    "nanna-opening": "https://www.sortiraparis.com/en/where-to-eat-in-paris/bars-cafes/articles/337914-nanna-the-cozy-literary-barge-with-a-library-and-a-bar-at-the-foot-of-notre-dame-cathedral",
    "babylone": "https://www.ysl.com/fr-fr/stores/saint-laurent-babylone-30307",
    "orangerie-visit": "https://www.musee-orangerie.fr/fr/visite/acces-horaires-tarifs",
    "orangerie-price": "https://www.musee-orangerie.fr/fr/visite/tarifs-orangerie",
    "monet": "https://www.musee-orangerie.fr/fr/programme/agenda/expositions/presentation/monet-peindre-le-temps",
    "grand-cafe": "https://www.legrandcafe-paris.com/",
    "pinault-remember": "https://www.pinaultcollection.com/en/boursedecommerce/remember-me",
    "pinault-kruger": "https://www.pinaultcollection.com/fr/boursedecommerce/history-tears",
    "shin": "https://www.pagesjaunes.fr/pros/64990741",
    "bouillon": "https://bouillonlesite.com/",
    "mitterrand-news": "https://www.artnewspaper.fr/2026/09/07/la-galerie-mitterrand-setend-avenue-matignon",
    "cartilage": "https://www.timeout.fr/paris/actualites/cartilage-nouveau-lieu-scenes-alternatives-ancien-cabaret-libanais-030526",
    "cartier": "https://www.fondationcartier.com/programme/exposition/le-temps-des-recoltes-ibrahim-mahama",
    "large": "https://www.large-emerige.fr/",
    "large-tourism": "https://parisjetaime.com/eng/culture/large-contemporary-art-ile-seguin-boulogne-billancourt-p4869"
  }
};
